name: Application Build&Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_react:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2.3.4  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      working-directory: ./client
      run: yarn install
    - name: build project
      working-directory: ./client
      run: yarn build
    
  build_nestjs:
    needs: build_react
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: yarn install
    - name: build project
      run: yarn build
    - name: Get current time
      uses: 1466587594/get-current-time@v2 
      id: current-time
      with:
        format: YYYY-MM-DDTHH-mm-ss # (1)
        utcOffset: "+09:00"
    - name: Show Current Time
      run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}" # (2)
      shell: bash
    - name: Generate deployment package
      run: zip -r deploy.zip .
    
  deploy_to_eb:
    needs: build_nestjs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Open Web Client Directory
      run: |
        ls -al
    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: gf-42labs
        environment_name: Gf42labs-env
        version_label: ${{ github.run_id }}
        region: ap-northeast-2
        deployment_package: deploy.zip
