name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: yarn install
    - name: build project
      run: yarn build
    - name: zip project
      run: zip -r deploy.zip .
    - name: Deploy to Elastic Beanstalk 
      uses: einaregilsson/beanstalk-deploy@v10
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: cp-admin-client
        environment_name: cp-client-dev
        version_label: ${{github.run_number}}
        use_existing_version_if_available: true
        region: ap-northeast-2
        deployment_package: build/deploy.zip
